### ISSUE TITLE
Change from a source to a filter?

### ISSUE THREAD

**Issue by rogueyoshi** [lilymonad/obs_mpris#1]
It might be better if you made this as a filter that modified the text source that it's attached to rather than having needing it as a whole different source.

**Comment by lilymonad** [comment]
I want to show the album jacket, so thought I'd register it as a source. But if you prefer to use it as a filter then yes why not, maybe I'd add a build target ?

**Comment by rogueyoshi** [comment]
It may not hurt to offer both the filter and the source in the same module if possible, obs-ndi does it.
